rhinstaller/anaconda-webui

docs/testing.rst

https://github.com/rhinstaller/anaconda/blob/fedora-39/docs/testing.rst

Put back docs/testing.rst content from the anaconda repository

---

test/README.rst
test/build-rpms

Resolves: https://issues.redhat.com/browse/INSTALLER-3796

Add TEST_SCENARIO to test against open anaconda PRs

---

Makefile

We want to start testing webui against fedora ELN https://github.com/cockpit-project/bots/pull/5585

tests: allow overriding the OS

---

src/components/Password.jsx
src/components/storage/DiskEncryption.jsx
src/components/users/Accounts.jsx
test/check-users
test/helpers/installer.py

This is the last bit of https://issues.redhat.com/browse/INSTALLER-3781
Also it tries to address some difficulties with tests, checking values, and debounce

Users: full name validation

---

.github/dependabot.yml
.gitmodules
docs/testing.rst
test/README.rst

Fallouts after the repo split.

Fix up some docs and infra files to reflect the repo structure

---

build.js
images/qr-code-feedback.svg
packaging/anaconda-webui.spec.in
src/components/installation/Feedback.jsx
src/components/installation/Feedback.scss
src/components/installation/InstallationProgress.jsx
src/components/installation/InstallationProgress.scss

In order to load the SVG image the build.js esbuild script had to be adjusted.
https://cockpit-logs.us-east-1.linodeobjects.com/pull-74-20231213-155623-1ca9887b-fedora-rawhide-boot/TestInstallationProgress-testBasic-installation-progress-complete-pixels.png

Add feedback section in the installation screen

---

src/apis/users.js
src/components/AnacondaWizard.jsx
src/components/users/Accounts.jsx
src/components/users/Accounts.scss
test/check-users
test/helpers/users.py

Root account

---

test/browser-layouts.json

This is keeping english and not some proper RTL language like Arabic but should be enough to identify overflows or other UI issues specific to this language group.

tests: generate screenshots with RTL language direction

---

packaging/anaconda-webui.spec.in
packit.yaml

Also it's not cockpit-storage but cockpit-storaged.
Remove obsolete comment.

packaging: fix double Requires of cockpit-storaged in the spec file

---

test/machine_install.py

We want to disable half automatic ks installations for Web UI, since these are not supported. This was getting in the way.
Resolves: https://issues.redhat.com/browse/INSTALLER-2816

tests: set payload through interactive defaults

---

src/components/storage/EncryptedDevices.jsx
test/helpers/storage.py

storage: fix password visibility toggle when clicking on 'eye' button

---

src/components/Error.jsx
src/components/app.jsx
test/check-basic

The report dialog was always showing 'undefined' when JS exceptions occured.

Fix Javascript error hanlding

---

src/components/storage/MountPointMapping.jsx
test/check-storage
test/helpers/installer.py

storage: do not overwrite request object structure - only extend it

---

src/actions/miscellaneous-actions.js
src/components/app.jsx
src/components/storage/CockpitStorageIntegration.jsx
src/reducer.js

Exceptions from front end are special in the sense that they contain stack trace.

Unify handling of backend and front end errors

---

src/actions/storage-actions.js
src/actions/users-actions.js
src/apis/storage.js
src/apis/storage_partitioning.js
src/components/AnacondaWizard.jsx
src/components/Common.jsx
src/components/app.jsx
src/components/review/ReviewConfiguration.jsx
src/components/review/StorageReview.jsx
src/components/steps.js
src/components/storage/CockpitStorageIntegration.jsx
src/components/storage/DiskEncryption.jsx
src/components/storage/InstallationDestination.jsx
src/components/storage/InstallationMethod.jsx
src/components/storage/InstallationScenario.jsx
src/components/storage/ModifyStorage.jsx
src/components/storage/MountPointMapping.jsx
src/components/users/Accounts.jsx
src/reducer.js

Wizards should not contain ideally any state, relative only to its children.

components: move steps to seperate file

---

src/apis/storage.js

localStorage does not contain this entry.

apis: Read storage-scenario-id from sessionStorage where it's stored

---

src/helpers/storage.js

Previously it was getting only the direct children and leaf elements, we want the whole tree.

storage: helpers: fix the calculation of device children

---

src/components/storage/CockpitStorageIntegration.jsx
test/check-storage

storage: cockpit-integration: do not overwrite request object structure - only extend it

---

src/actions/storage-actions.js
src/apis/storage.js
src/apis/storage_devicetree.js
src/components/review/StorageReview.jsx
src/components/review/StorageReview.scss
src/helpers/storage.js
src/reducer.js
test/check-storage
test/helpers/review.py

[Some changes caught by pixel tests.
](https://github.com/rhinstaller/pixel-test-reference/compare/29ceb682de67763afc72c168807b4c9ed8098034..d564d7da547e2bb06e3fa7a907025b71cf40bda6)

Show the storage layout in the review page for all scenarios

---

src/actions/storage-actions.js
src/apis/storage.js
src/components/AnacondaWizard.jsx
src/components/localization/InstallationLanguage.jsx
src/components/review/ReviewConfiguration.jsx
src/components/storage/DiskEncryption.jsx
src/components/storage/InstallationMethod.jsx
src/components/storage/InstallationScenario.jsx
src/components/storage/MountPointMapping.jsx
src/components/users/Accounts.jsx
src/reducer.js

Otherwise applying the new one is problematic for the 'use-free-space' scenario.

storage: reset the partitioning when mounting DiskEncryption

---

test/machine_install.py

Import it from the correct bots directory.

test: Fix testvm import

---

src/components/AnacondaPage.jsx
src/components/AnacondaWizard.jsx
src/components/localization/InstallationLanguage.jsx
src/components/review/ReviewConfiguration.jsx
src/components/steps.js
src/components/storage/DiskEncryption.jsx
src/components/storage/InstallationMethod.jsx
src/components/storage/MountPointMapping.jsx
src/components/users/Accounts.jsx

Laying on top of https://github.com/rhinstaller/anaconda-webui/pull/321

Generic improvements around page initialization and definitions

---

src/actions/storage-actions.js
src/apis/storage_devicetree.js
src/components/review/Common.jsx
src/components/review/ReviewConfiguration.jsx
src/components/review/StorageReview.jsx
src/components/storage/CockpitStorageIntegration.jsx
src/components/storage/Common.jsx
src/components/storage/InstallationDestination.jsx
src/components/storage/InstallationScenario.jsx
src/components/storage/ModifyStorage.jsx
src/components/storage/MountPointMapping.jsx
src/components/storage/ReclaimSpaceModal.jsx
src/reducer.js
test/check-existing-system
test/check-storage-reclaim
test/helpers/review.py

review: show existing systems affected by deleted partitions

---

src/components/storage/ReclaimSpaceModal.jsx

I was not able to test this with integration tests, as I was not able to create a mock bitlocker partition from linux.
Tested with a real Windows qcow, which I can share with the reviewer.

storage: give hint on how to resize bitlocker encrypted windows partitions

---

Makefile
src/components/review/StorageReview.jsx
test/check-existing-system
test/helpers/review.py

review: show resized partitions that belong to an OS

---

test/check-basic
test/check-existing-system
test/check-language
test/check-progress
test/check-review
test/check-storage-basic
test/check-storage-cockpit
test/check-storage-encryption
test/check-storage-mountpoints
test/check-storage-reclaim
test/check-users

Part of https://github.com/rhinstaller/anaconda-webui/pull/365

tests: reorganize some storage related test to have clearer purpose

---

test/anacondalib.py
test/check-existing-system
test/check-storage-basic
test/helpers/storage.py

https://fedoraproject.org/wiki/Test_Results:Fedora_41_Rawhide_20240706.n.1_Installation#Test_Matrix

tests: map test matrix from Fedora QA team to our tests

---

src/components/storage/CockpitStorageIntegration.jsx
src/components/storage/InstallationMethod.jsx
test/check-storage-basic
test/check-storage-cockpit
test/check-storage-mountpoints
test/helpers/storage.py

Re-add alert confirmation before Cockpit Storage

---

src/actions/storage-actions.js
src/apis/storage_devicetree.js
src/apis/storage_partitioning_automatic_resizable.js
src/components/review/StorageReview.jsx
src/components/storage/CockpitStorageIntegration.jsx
src/components/storage/Common.jsx
src/components/storage/EncryptedDevices.jsx
src/components/storage/InstallationScenario.jsx
src/components/storage/MountPointMapping.jsx
src/components/storage/ReclaimSpaceModal.jsx
src/helpers/storage.js
src/reducer.js

Obsoletes https://github.com/rhinstaller/anaconda-webui/pull/177

storage: display names not IDs in the storage screens

---

src/components/storage/CockpitStorageIntegration.jsx

Update text for cockpit storage confirmation modal

---

src/components/storage/InstallationScenario.jsx
src/components/storage/InstallationScenario.scss

storage: increase the radio button spacing in the scenario selection group

---

src/components/review/ReviewConfiguration.jsx
src/components/storage/InstallationScenario.jsx
test/check-existing-system
test/check-progress
test/check-review
test/check-storage-basic
test/check-storage-reclaim
test/helpers/installer.py
test/helpers/review.py

review: switch from confirmation modal to checkbox

---

src/components/storage/ReclaimSpaceModal.jsx

storage: some enhancements on reclaim dialog after designer feedback

---

src/components/Password.jsx
src/components/users/Accounts.jsx

Swipe for checking before after comparison: https://github.com/rhinstaller/pixel-test-reference/compare/e896d2abd630e526d3dfa8893ec4fc885fd25820..11dffb5a3d4faba8e26ee07ea9531f87abbcb19f#diff-0e0624114264f1078bfb8d89e1aac41c5bf795661e7d3e87a4c5a7f1157a2879

users: storage: increase spacing between password fields

---

src/components/storage/Common.jsx
src/components/storage/InstallationScenario.jsx
src/components/storage/MountPointMapping.jsx
src/helpers/utils.js
test/check-storage-mountpoints
test/helpers/storage.py

Since we are addressing devices through their device-id it's now possible to utilize for installation devices with the same name.

Allow having duplicate device names

---

src/components/storage/MountPointMapping.jsx

storage: mount point assignment: show partition labels in device selection

---

test/anacondalib.py

Issue with Toolbx is that it shares the user libvirt socket so if libvirt is started on the host system first the container will use this host libvirt socket and won't start its own.
That works fine until container starts creating libvirt resources which are not shared with the host. In that case libvirt fails to get these resources.
To avoid this issue use /run/host/var/tmp when available so the /var/tmp is still used but still accessible by the host system. The /run/host is a way how toolbx can access host system resources so what is there is available in both container and host system.
Similar fix is already part of the Cockpit tests:
https://github.com/cockpit-project/bots/pull/6941

Fix tests executed in Toolbx with host libvirt

---

.gitignore

Follow up for 48378d053a23c43073bcd127d92e2102d65b21fe.

Respect all prefixes for *updates.img in the root of the repo

---

test/check-storage-home-reuse

home reuse: add a test checking rebooted installed system

---

src/components/steps.js
src/components/storage/DiskEncryption.jsx
src/components/storage/StorageConfiguration.jsx
test/check-basic
test/check-review
test/check-storage-basic
test/check-storage-encryption
test/check-storage-mountpoints-lvm
test/helpers/installer.py
test/helpers/utils.py

The motivation behind this was to prepare the ground to introduce more configuration options, like `swap` option.

Move disk encryption under generic storage configuration step

---

src/components/review/StorageReview.jsx

So that the user get's informed for subvolumes.

review: show device type if it's formatted as btrfs

---

test/check-existing-system

The review screen now shows the debian affected partition.

tests: extend test for dual booting with debian

---

firefox-theme/default/user.js
firefox-theme/live/user.js

firefox: disable builtin Password Manager / Password Generation

---

src/components/storage/CockpitStorageIntegration.jsx
src/components/storage/Common.jsx
test/anacondalib.py
test/check-existing-system
test/check-storage-mountpoints-raid

tests: implement e2e tests for testing RAID1 on partition level with LVM

---

src/apis/storage_devicetree.js
src/components/review/StorageReview.jsx
src/components/storage/EncryptedDevices.jsx
src/components/storage/InstallationScenario.jsx
src/components/storage/MountPointMapping.jsx
test/check-storage-home-reuse
test/check-storage-mountpoints
test/check-storage-mountpoints-btrfs
test/check-storage-mountpoints-raid
test/helpers/storage.py

Support 'home' reuse when '/home' lives on encrypted partition

---

firefox-theme/live/chrome/userChrome.css
firefox-theme/live/user.js

I've modified the theme in a few ways, at least for `live`; this could apply to `default` too, perhaps.
1. I fixed a parsing error. I _think_this works for that setting, but I'm not sure.
2. I reworked the way the UI is hidden when there's 1 tab.

Firefox 133 fixes

---

test/README.rst
test/anacondalib.py
test/check-storage-home-reuse
test/check-storage-home-reuse-e2e
test/check-storage-mountpoints
test/check-storage-use-free-space-e2e
test/helpers/operating_systems.py
test/machine_install.py
test/run
test/webui_testvm.py

See also https://github.com/cockpit-project/bots/pull/7182

tests: introduce run_boot decorator for boot mode-specific tests

---

.github/workflows/nightly.yml
Makefile
test/README.rst
test/download-iso
test/machine_install.py
test/prepare-updates-img
test/run
test/vm.install

Rebased on top of: https://github.com/rhinstaller/anaconda-webui/pull/592

infra: introduce daily cron job to trigger tests against latest compose

---

src/components/AnacondaWizard.jsx
src/components/app.jsx
test/check-storage-cockpit

This fixes the 'Launch storage editor' button being disabled on Live ISO.
Resolves: rhbz#2336488

Ensure that URL path is always set when loading the app

---

.github/workflows/nightly.yml
.github/workflows/test-compose.yml

Tested in my fork: https://github.com/KKoukiou/anaconda-webui/actions/runs/13306877864

infra: support specifying which compose to test with parameter to the workflow

---

test/check-storage-cockpit
test/run

And revert https://github.com/rhinstaller/anaconda-webui/pull/608 that landed broken.
Fix up for: c03f7fc44

test: exit with correct exit code in test/run script

---

src/components/storage/CockpitStorageIntegration.jsx
src/components/storage/scenarios/UseFreeSpace.jsx
test/check-storage-cockpit
test/check-storage-mountpoints-raid-e2e
test/check-storage-reclaim-e2e
test/helpers/storage.py

storage:  some cockpit-storage page improvements for RAID detection

---

test/anacondalib.py
test/check-storage-erase-all
test/check-storage-reclaim
test/helpers/operating_systems.py

This way storage rescanning happens after partitioning in the setup.

tests: perform disk partitioning with the _{method_name}_partition_disk

---

src/components/storage/CockpitStorageIntegration.jsx
src/components/storage/ReclaimSpaceModal.jsx
src/components/storage/scenarios/EraseAll.jsx

This was generating some funny and broken translations.
Relevant to: rhbz#2351026

Fix translations that were prepared as string concatenation

---

Makefile

See https://github.com/cockpit-project/cockpit/commit/54f87df7b7b5428c66bae8c1b91f30963c8bdb45

Adjust build target for translations: html2po was converted to python

---

Makefile

See https://github.com/cockpit-project/cockpit/commit/3288a3e2d21ae1bf674875ba6c9f9daf0e93c3fc

Adjust build target for translations: manifest2po was converted to python

---

src/components/review/ReviewConfiguration.jsx
src/components/storage/HelpAutopartOptions.jsx
src/components/storage/InstallationScenario.jsx
src/components/storage/scenarios/EraseAll.jsx
src/components/storage/scenarios/MountPointMapping.jsx
src/components/storage/scenarios/ReinstallFedora.jsx
src/components/storage/scenarios/UseConfiguredStorage.jsx
src/components/storage/scenarios/UseFreeSpace.jsx

This fixes the untranslated strings in the installation scenario selection.
Resolved: rhbz#2351026

Ensure that translations are not requested at file load time

---

src/components/review/StorageReview.jsx
src/helpers/storage.js
test/check-storage-cockpit

storage: support disks with filesystem directly on them for installation

---

src/components/localization/InstallationLanguage.jsx
src/index.js
test/check-language
test/helpers/language.py

language: fix markup to specify lang for language list entries

---

src/components/storage/scenarios/ReinstallFedora.jsx
test/check-storage-mountpoints

Do not offer home reuse if there is no GPT disk

---

pyproject.toml
src/components/storage/scenarios/ReinstallFedora.jsx
test/check-storage-home-reuse
test/helpers/storage.py

Depends on backend update: https://github.com/rhinstaller/anaconda/pull/6331
The first two commits are part of a separate PR: https://github.com/rhinstaller/anaconda-webui/pull/746

Add test for other OS (Win, MacOS) detection

---

src/apis/runtime.js

WebUI folowup for new ProductData API:[6284]( https://github.com/rhinstaller/anaconda/pull/6284)

Migrate isFinal to new ProductData API

---

Makefile
test/run
test/vm.install

This enables also: https://github.com/rhinstaller/anaconda/pull/6357

tests: allow combined scenarios for cross project testing     

---

test/check-storage-reclaim

New payload is bigger, we need more space. [1]
[1] https://github.com/cockpit-project/bots/pull/7645

tests: increase the size of the disk image in testDeletePartition

---

src/components/review/StorageReview.jsx
src/helpers/storage.js
test/check-review
test/check-storage-cockpit

after cockpit storage:
efi after cockpit storage:

Review screen bootloader location

---

docs/release.rst

https://github.com/KKoukiou/anaconda-webui/blob/main/docs/release.rst

docs: add release guidelines

---

src/apis/storage_devicetree.js
src/components/storage/CockpitStorageIntegration.jsx
src/components/storage/InstallationScenario.jsx
src/components/storage/MountPointMapping.jsx
src/hooks/Storage.jsx
test/check-storage-home-reuse
test/check-storage-mountpoints
test/helpers/utils.py

Related: rhbz#2353002
Depends on https://github.com/rhinstaller/anaconda/pull/6312

Make mount point constraints depending on devices and disk selection

---

src/actions/localization-actions.js
src/apis/localization.js
src/components/AnacondaWizard.jsx
src/components/AnacondaWizardFooter.jsx
src/components/Error.jsx
src/components/HeaderKebab.jsx
src/components/installation/Feedback.jsx
src/components/installation/InstallationProgress.jsx
src/components/localization/Common.jsx
src/components/localization/InstallationLanguage.jsx
src/components/localization/InstallationLanguage.scss
src/components/localization/Keyboard.jsx
src/components/review/ReviewConfiguration.jsx
src/components/storage/DiskEncryption.jsx
src/contexts/Common.jsx
test/check-language
test/helpers/language.py

This needs: https://github.com/rhinstaller/anaconda/pull/6384 
Tested on:
[1] LXQT https://pagure.io/fedora-lxqt/SIG/issue/4

Implement Keyboard selection for non Gnome variants

---

src/components/storage/scenarios/ReinstallFedora.jsx
test/check-storage-home-reuse

Depends on https://github.com/rhinstaller/anaconda/pull/6411
The anaconda/backend part can be released before the webui part.

Home reuse mbr

---

Makefile

Follow up for: 550256513832846754d185783eb7f1e3ff7c36ea

build: prepare npm dependencies before building the tarball

---

test/check-basic
test/check-language
test/check-progress
test/check-review
test/check-storage-basic
test/check-storage-cockpit
test/check-storage-cockpit-e2e
test/check-storage-encryption
test/check-storage-erase-all
test/check-storage-erase-all-e2e
test/check-storage-home-reuse
test/check-storage-home-reuse-e2e
test/check-storage-mountpoints
test/check-storage-mountpoints-btrfs
test/check-storage-mountpoints-lvm
test/check-storage-mountpoints-raid
test/check-storage-mountpoints-raid-e2e
test/check-storage-reclaim
test/check-storage-reclaim-e2e
test/check-storage-use-free-space-e2e
test/check-users

Added docstrings to several test cases using the standard format: Description, Setup, Test Steps, and Expected Results. Improves readability and test documentation consistency.

tests: Add structured docstrings to Web UI tests

---

Makefile

https://github.com/cockpit-project/cockpit/pull/22047

infra: GITHUB_BASE is now set within ./test/common/make-bots

---

src/components/storage/InstallationDestination.jsx
src/components/storage/InstallationMethod.jsx
src/components/storage/InstallationScenario.jsx
src/components/storage/scenarios/EraseAll.jsx
test/check-storage-basic

Partially resolves: https://issues.redhat.com/browse/INSTALLER-4084
Before:
After:

components: storage: hide all scenarios when disk selection is not valid

---

src/components/storage/InstallationMethod.jsx
src/components/storage/InstallationScenario.jsx
src/components/storage/scenarios/EraseAll.jsx
test/check-storage-basic

This partially reverts commit 36a34c621b5084551aee59bd42b14dd76f6ae8f8.

Check scenario availability as this is utilized for disabling the 'Next' button

---

src/actions/users-actions.js
src/components/AnacondaWizardFooter.jsx
src/components/Password.jsx
src/components/review/ReviewConfiguration.jsx
src/components/users/Accounts.jsx
src/components/users/Accounts.scss
src/helpers/users.js
src/reducer.js
test/check-users
test/helpers/users.py

This is rebased on top of https://github.com/rhinstaller/anaconda-webui/pull/918 because it's a new flake and does not let tests pass.

Support skipping account creation in the users screen (rhbz#2352491)

---

test/webui_testvm.py

See bots commit:
commit b365eb61d03b85314df3e7241547ed7915207d68
Author: Allison Karlitskaya <allison.karlitskaya@redhat.com>
Date:   Wed Jul 30 10:26:05 2025 -0400
machine: rework ssh argument handling a bit

tests: adjust to removed arguments from ssh_connection in bots
