rhinstaller/anaconda-webui

test/helpers/installer.py
Resolves: INSTALLER-3792
In my local tests the flakes disappeared, but some tests timeouted on the condition.
=> tests: address pixel tests flakiness with unloaded logo image

test/check-basic, test/check-storage
The https://github.com/rhinstaller/anaconda/pull/5327 migrated to this new repository.
=> webui: fix waiting for disabled button in some tests

test/check-basic, test/check-storage, test/helpers/installer.py, test/helpers/utils.py
Port of https://github.com/rhinstaller/anaconda/pull/5331 to the new repository.
The first two commits are from this PR: https://github.com/rhinstaller/anaconda-webui/pull/50
With this PR, adding
```
pretend_live_iso(self, i)
```
(which effectively hides welcome and accounts step in the installer) before `open()` of all the tests where it makes sense the tests are still passing (except for pixel tests). So they should break less easily when adding some other step in the future (as it happened when I was adding users spoke).
As a follow-up the installer.py helper could be a bit cleaned and re-factored and maybe some tests run in multiple variants.
=> Webui tests more robust going back and variant agnostic

test/anacondalib.py, test/check-language, test/check-review, test/check-storage, test/check-users, test/helpers/installer.py
This is not being always loaded.
https://issues.redhat.com/browse/INSTALLER-3792
Leave a single test in test/check-progress to check that icon till we figure out the issue.
=> tests: temporarily ignore in pixel tests the logo

src/components/storage/InstallationDestination.jsx, test/check-storage, test/helpers/storage.py
Also change the notification type to toast for the 'no changes detected', in order to avoid moving UI elements when the notification appears.
This also fixes a bug, where the 'not additional disks detected' notification appears while re-scan is in progress.
Resolves: INSTALLER-3727
Resolves: INSTALLER-3742
=> storage: show toast notification when disks selection changed

test/README.rst, test/prepare-updates-img
This enables us to test against locally built anaconda-core RPM to validate features that touch front end and backend.
Resolves: INSTALLER-3794
=> tests: allow adding extra local RPMs to the updates.img

src/components/AnacondaWizard.jsx, src/components/users/Accounts.jsx, src/scripts/encrypt-user-pw.py, test/check-users
NOTE: using the same method as the current Gtk GUI
This is the PR https://github.com/rhinstaller/anaconda/pull/5321 migrated to the new repository.
=> webui: crypt user password by default before passing it to backend

src/components/review/ReviewConfiguration.jsx, src/components/users/Accounts.jsx, src/components/users/Accounts.scss, test/check-users, test/helpers/users.py
The PR was originally open on anaconda repository and has some history and discussion there: https://github.com/rhinstaller/anaconda/pull/5305
=> Validate user account value

packit.yaml
Trigger the build in Fedora Koji build system as a reaction to a new dist-git commit.
Create a new update in Fedora Bodhi for successful Koji build.
=> packit: add koji_build and bodhi_update targets

test/build-rpms, test/machine_install.py
See https://copr.fedorainfracloud.org/coprs/g/rhinstaller/Anaconda/
With this change we will be testing latest commited changes in the core repository.
=> tests: pull anaconda-core from COPR build from master and include firefox dependencies

test/anacondalib.py
Cockpit's cleanup handlers are responsible among others for cleaning up per-test added disks, such as SCSI disks. We need to invoke the parent class setUp after adding the anaconda specific cleanup handers.
This sequence guarantees that re-scanning occurs at the very end of the cleanup process, after all disks are removed.
This was causing problems in CI and regressed with 899d47eb8d22ed2bfa52c215dbec31fa7efe1abf.
=> tests: execute anaconda specific cleanup handlers after the cockpit's ones

test/helpers/storage.py
Tests in CI often timeout on this, the journal does not seem suspicious, let's give it some more time.
Also add a check for the re-scan button getting initially disabled to avoid race conditions where we skip the 'rescan button disabled' condition before it even got into that state.
=> tests: increase timeout for waiting for storage re-scan to finish

src/components/Password.jsx
When saving into a variable a primitive data type, then the reference never changes unless the value changes.
=> No need to use useMemo when the resolved value is a primitive data type

test/vm.install
I am not sure when this broke but dnf download before the mkdir made the /var/tmp/build directory owned by root so builder wouldn't be able to create a directory for SRPMS.
https://cockpit-logs.us-east-1.linodeobjects.com/pull-19800-20240112-091849-b22ddb10-fedora-rawhide-boot-cockpit-pr-19800-rhinstaller-anaconda-webui/log.html
=> Reverse gating mkdir failure

test/vm.install
When testing in a Cockpit storage PR scenario we also need cockpit-ws, cockpit-bridge installed. This was broken by b14ac44f16c3414f569f as that changed the cockpit-pr scenario to not install the bridge/ws and fedora-logos anymore.
Note that this does not fix the gating tests, locally I get stuck on:
But before I got:
```
[anaconda root@localhost ~]# /usr/bin/bash /usr/libexec/webui-desktop -t default -r 1 /cockpit/@localhost/anaconda-webui/index.html
Cleaning up existing Anaconda Firefox profile directory.
/usr/libexec/webui-desktop: line 100: /usr/libexec/cockpit-ws: No such file or directory
```
=> test: install missing packages also in gating scenario

packaging/anaconda-webui.spec.in
We can't use Firefox in ELN because it was removed. This Requires is dragging it back.
https://github.com/minimization/content-resolver-input/pull/1061
=> Exclude Firefox on ELN

src/apis/storage_devicetree.js, src/components/AnacondaWizard.jsx, src/components/storage/MountPointMapping.jsx, test/check-storage, test/helpers/storage.py
Depends on Anaconda backend API update: https://github.com/rhinstaller/anaconda/pull/5372
=> Make boot not required

src/components/storage/MountPointMapping.jsx
Adds two commits on top of https://github.com/rhinstaller/anaconda-webui/pull/95 that should make sure constraints without mount point (eg biosboot partition) won't mess up Mount Point Assignment screen.
=> Handle bootloader partition constraints

packit.yaml
As pointed out in https://bugzilla.redhat.com/show_bug.cgi?id=2260395#c18 , anaconda and anaconda-webui contain often inter-dependent changes which *must* be submitted as a single update: https://docs.fedoraproject.org/en-US/fesco/Updates_Policy/#updating-inter-dependent-packages
Packit unfortunately does not support this packit/packit#1870 so we need to do this manually.
For release guidelines read https://github.com/rhinstaller/anaconda/blob/master/docs/release.rst#the-mostly-automated-build-path
=> Revert koji automation done by packit

packaging/anaconda-webui.spec.in
The newly used GetMountPointConstraints API needs latest anaconda.
=> packaging: bump anaconda core requirement version

test/anacondalib.py
Without the patch the filesystem on a partition is not wiped and in a following test, if a partition without a filesystem is created on the same offset the original filesystem is detected errorneously.
=> Clear partitions during test cleanup better

src/helpers/exit.js
There were change in Anaconda core which accidentally added a new line to the pid file created. It will be fixed also there but I think this worth to fix this here also.
Issue was introduced by https://github.com/rhinstaller/anaconda/commit/1843885f6b70278790bdb3cd2ecfe43a2cb35846 .
Resolves: rhbz#2262413
=> Fix issue when browser pid file containes newline

test/vm.install
=> Anaconda needs latest pykickstart but image refresh is currently blocked on blivet regression

packaging/anaconda-webui.spec.in
Also udisks2-lvm is wrong - it's udisks2-lvm2.
=> packaging: recommended dependencies from cockpit-storage are installed by default

.flake8, .gitignore, Makefile, build.js, firefox-theme/default/user.js, firefox-theme/live/user.js, pyproject.toml, scripts/makeupdates, src/scripts/encrypt-user-pw.py, test/anacondalib.py, test/check-basic, test/check-language, test/check-progress, test/check-review, test/check-storage, test/check-users, test/helpers/installer.py, test/helpers/language.py, test/helpers/password.py, test/helpers/progress.py, test/helpers/review.py, test/helpers/step_logger.py, test/helpers/storage.py, test/helpers/users.py, test/helpers/utils.py, test/machine_install.py, test/run, test/vm.install, test/webui_testvm.py
This is useful to spot errors like the missing `import time`, and keep a consistent code style.
This also prepares us for the next step, see https://github.com/cockpit-project/starter-kit/commit/15be8835955f8
=> Introduce flake8, ruff, use shared test/static-code

HACKING.rst, Makefile, build.js, firefox-theme/default/chrome/userChrome.css, firefox-theme/live/chrome/userChrome.css, test/run, test/webui_testvm.py
stylelint 16 causes a deadlock/crash in esbuild [1]. There's no movement
on that issue, and we want stylelint 16 to be able to support the
Browser Baseline 2023.
Follow https://github.com/cockpit-project/cockpit/commit/1a28b31828e and
move the linters into test/static-code. This also starts to lint files
which are outside of esbuild's realm, such as documentation and
examples.
[1] https://github.com/evanw/esbuild/issues/3542
Taken from https://github.com/cockpit-project/starter-kit/commit/15be8835955f8
---
This will unblock the next round of stylelint refresh, see PR #156 . It also unblocks keeping up with cockpit.git shared files, see #166
=> Move eslint/stylelint to static-code tests

test/check-basic, test/check-language
Seems like the chromium used for the tests crashes when the Report dialog gets opened with the full journal input.
=> tests: cleanup journal before opening the report modal

packaging/anaconda-webui.spec.in, src/components/AnacondaWizard.jsx, src/components/review/ReviewConfiguration.jsx, src/components/storage/CockpitStorageIntegration.jsx, src/components/storage/CockpitStorageIntegration.scss, src/components/storage/InstallationMethod.jsx, src/components/storage/InstallationScenario.jsx, src/components/storage/ModifyStorage.jsx, test/check-storage, test/helpers/installer.py, test/helpers/storage.py, test/vm.install
=> storage: Add new integration layer between anaconda and cockpit storage

test/check-progress
Last missing pixel tests was the in progress, which was sometimes failing. The logo sometimes fails to load in the tests.
=> tests: ignore logo in the tests everywhere

src/components/storage/MountPointMapping.jsx
Since the following commit the is validation check in the back-end for if / is empty. We should not force re-formatting in the front-end.
commit 8dbfc48847dd764fa41f647610ce7f23fc98d3a4
Author: Vojtech Trefny <vtrefny@redhat.com>
Date:   Mon Jan 22 11:06:00 2024 +0100
Allow reusing existing "empty" filesystems for /
=> storage: do not force reformatting /

src/components/AnacondaWizard.jsx, test/check-storage
This prevents the 'Use configured storage' scenario from disappearing when selecting another scenario. The 'Use configured storage' should disappear when the applied partitioning is not longer the one created from the storage page.
=> storage: keep all scenarios in the partitioning object mapping

src/components/AnacondaWizard.jsx, src/components/review/ReviewConfiguration.jsx, src/components/review/StorageReview.jsx, src/components/storage/CockpitStorageIntegration.jsx, src/components/storage/CockpitStorageIntegration.scss, src/components/storage/InstallationMethod.jsx, src/components/storage/InstallationScenario.jsx, src/components/storage/InstallationScenario.scss, test/check-storage
When the user exits the cockpit-storage, they need to see somewhere a review of their actions. Show that as a hint item, in the scenario description.
=> storage: show the partitioning request review for the 'Use configured storage'

packaging/anaconda-webui.spec.in, src/components/installation/InstallationProgress.jsx, test/check-progress
blocker: https://github.com/rhinstaller/anaconda/pull/5329
=> webui: change hardcoded installation phases to new API

src/components/app.jsx, src/components/app.scss, test/check-storage
=> storage: fix modal backdrops from modals from cockpit-storage to extend to full page

pyproject.toml, test/helpers/installer.py, test/helpers/language.py, test/helpers/storage.py, test/webui_testvm.py
These aren't unused, but discovered/enumerated by `unittest` or `pytest`.
=> lint: Ignore test functions in vulture

test/check-storage
The only check hindering us from doing that was the there was no partitioning pre-selected.
This line would fail the test if it ran more than once in a row, as the previously created partitioning would be detected for re-using.
=> tests: switch testEncryptedUnlockRAIDonLUKS to non-destructive

test/check-storage
This can slightly change with payload updates, let's not fail on this.
=> tests: ignore pixel area showing the exact disk size the installation needs

src/actions/network-actions.js, src/apis/network.js, src/components/Common.jsx, src/components/review/Hostname.jsx, src/components/review/ReviewConfiguration.jsx, src/reducer.js, test/check-basic, test/check-review, test/check-storage, test/check-users, test/helpers/network.py, test/helpers/review.py
=> Hostname handling

src/components/AnacondaPage.jsx, src/components/AnacondaWizard.jsx, src/components/AnacondaWizardFooter.jsx, src/components/storage/DiskEncryption.jsx, src/components/storage/MountPointMapping.jsx
These notifications are page specific are belong better to the page wrapper, rather than the global AnacondaWizard component.
With this change the notifications are now reset / removed when changing pages. This is the desired behavior, as failures should appear only dynamically after clicking 'Next'.
=> Move stepNotification to the AnacondaPage component

test/vm.install
This reverts commit fe4a11f53d07014407e238ff5acce0ca8ea12ea3.
=> Revert "tests: download cockpit-storaged from custom COPR till release 311"

test/anacondalib.py
Running tests locally would otherwise use geolocation to determine the language, and might end up putting the UI into Finnish.  The tests of course expect English button labels, etc.
=> test: Reset the language at the start of each test

src/apis/storage.js, test/check-storage, test/helpers/installer.py, test/helpers/storage.py
The UI remembers the encryption choice from the last created partitioning. Since the tests are non-destructive this can create test failures, since tests expect the 'encryption' checkbox to be disabled at start.
For fixing that this commit introduces a callback on the disk encryption page.
For implementing the later we needed to solve a circular import scenario, therefore we stopped importing the Installer* classes from the Storage helpers file.
=> tests: some improvements for non-destructive tests

package.json
It's not used by anything. This avoids some unnecessary dependabot noise.
---
Context: I recently eliminated date-fns from cockpit's `timeformat` lib, see https://github.com/cockpit-project/cockpit/pull/20671 and https://github.com/cockpit-project/cockpit/pull/20685 . I am now dropping this npm dependency from all our projects.
=> package.json: Drop date-fns

src/components/review/ReviewConfiguration.jsx, test/check-review, test/helpers/review.py
If a device is encrypted is shown as a column in the storage overview.
=> review: remove 'Disk encryption' section and conditionally hide 'Account'

test/check-storage-cockpit
Ignoring just some lines was not sufficient.
=> tests: ignore the whole hint list in pixel test for cockpit integration

test/run
The are a few more TEST_SCENARIOS values aside from 'expensive' and 'other'. Such an example are the anaconda-pr-* and cockpit-pr-* scenarios, which are defined when we trigger Web UI tests from anaconda core and cockpit repositories respectively.
=> infra: run all tests when triggered with non bots defined scenario

test/run
Dont move to next condition if we matched one already. Commit e04d939dbfabd5aec357ca108395d40ae72fd7fa incorrectly introduced a new case, which matched always because of the ;;$.
From man bash:
Using ;;& in place of ;; causes the shell to test
the next pattern list in the statement, if any, and execute any associated list on a successful match.
=> tests: fix test scenario picking always all tests

Makefile, package.json, src/components/Error.jsx, src/components/storage/CockpitStorageIntegration.jsx, test/check-basic, test/check-storage-basic
See cockpit-project/cockpit#20832
Drop chrome-remote-interface NPM dependency.
Explicitly add a "glob" devDependency to follow suit with cockpit-project/cockpit@680decc155a
It was previously used implicitly through a transient dependency of something else, but our esbuild po-plugin uses it explicitly.
=> test: Move from CDP to BiDi

src/actions/storage-actions.js, src/components/storage/ReclaimSpaceModal.jsx, src/components/storage/ReclaimSpaceModal.scss, test/check-storage-reclaim, test/helpers/storage.py
This needs to be improved with human readable strings for partition labels once https://github.com/storaged-project/blivet/issues/1258 is implemented.
Windows (missing FS types because it's mocked disk)
Fedora
=> storage: reclaim dialog: show format type not device type

src/actions/storage-actions.js
This happens when there are deleted backing files from loop devices.
Ex:
$ cat /sys/block/loop0/loop/backing_file
/home/vtrefny/disk.img2 (deleted)
Resolves: rhbz#2308278
=> storage: fix crash when device path is not existing

test/check-existing-system, test/helpers/storage.py
Some tests use the images for ubuntu/debian/fedora from bots as backing files for target disks. The partitions on this disk can change with image refreshes, let's not bother about partition current sizes in reclaim dialog.
=> test: stop making assumptions about the partition sizes of installed images

test/vm.install
We don't need other packages because these only have dependencies or they have GTK UI. However, we do want to keep tui code even when Web UI is the only requested option as the fallback solution.
=> Add anaconda-tui package to updates-image

src/components/localization/InstallationLanguage.jsx, test/check-language
When switching back to EN_US after an RTL language choice, the UI previously kept the old language direction.
=> localization: update the language direction also when switching back to EN_US

test/vm.install
This reverts commit d71b0dde6b988a5de2fa07fd8cff106904ce8bc9.
=> Revert "test: bring latest available python3-kickstart till version 358 is available

packaging/anaconda-webui.spec.in
Fedora 41 does not contain that version, and also we don't plan to rebase there anymore, so it does not really matter.
Also clean up the specfile from conditions for Fedora < 41.
=> build: spec: require anaconda-core 42.5 only on fedora 42

test/vm.install
All pieces need to have the same version, otherwise the modules will likely not load, or UDisks2 will crash.
This should fix failures like these in https://cockpit-logs.us-east-1.linodeobjects.com/pull-6954-50025d8c-20241006-232043-fedora-rawhide-boot-other-rhinstaller-anaconda-webui/log.html#23
```
> warn: Can't enable storaged btrfs module Error initializing module 'btrfs': /usr/lib64/udisks2/modules/libudisks2_btrfs.so: undefined symbol: udisks_mdraid_set_consistency_policy
> warn: Can't enable storaged lvm2 module Error initializing module 'lvm2': /usr/lib64/udisks2/modules/libudisks2_lvm2.so: undefined symbol: udisks_mdraid_set_consistency_policy
```
=> test: Update all of udisks2, not just the lvm2 and btrfs modules

test/vm.install
Wayland changes bring many new dependencies, that if installed through updates.img, they cause multiple issues.
Work with the anaconda backend that already reached rawhide temporarily.
=> tests: do not update the anaconda packages till the wayland work reaches rawhide

Makefile, packaging/anaconda-webui.spec.in, src/systemd/webui-cockpit-ws.service, test/anacondalib.py, test/machine_install.py, test/vm.install, webui-desktop
Do not start firefox in the VM for remote installations. So far remote installations are used only for testing. Let's abuse this and switch firefox instance in the VM with a plain sleep, to avoid the crash. [1]
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2320964
=> Fix bridge crashing installation on boot.iso

firefox-theme/default/user.js, webui-desktop
Separating WebUI stuff from PR:https://github.com/rhinstaller/anaconda/pull/5058
=> Dont run browser as root

src/components/storage/ReclaimSpaceModal.scss
When there isn't enough vertical height to show all the partitions (when there are a lot of partitions), make the list of partitionsscroll instead of the body of the modal.
Screenshot, where I attached a Windows VM as a disk image and set the height to be artificially short as to trigger the overflow:
Note the scrollbar on the right, as it is attached to the list instead of the modal.
=> reclaim: Make the list scroll instead of the modal body

Makefile, extlinks.desktop, firefox-ext, firefox-theme/default/user.js, firefox-theme/extlink/user.js, firefox-theme/live/user.js, packaging/anaconda-webui.spec.in, src/components/Error.jsx, src/components/HeaderKebab.jsx, src/components/app.jsx, src/components/installation/Feedback.jsx
[AwesomeScreenshot-10_9_2024,6_00_35PM.webm](https://github.com/user-attachments/assets/e544f3fc-f63c-4ad5-9ccc-f12a65399dce)
=> Spawn new Firefox for external page links utilizing MimeType=x-scheme-handler/extlink

src/components/storage/CockpitStorageIntegration.jsx
Previously we were resetting the checkStep prematurely, therefore causing a UI flicker between success and error mode in the cockpit storage integration exiting dialog.
Moving the checkStep reset before the 'prepare partitioning' step solves this issue.
=> storage: cockpit: fix UI flickering when exiting cockpit storage

test/check-review, test/check-storage-cockpit, test/check-storage-home-reuse, test/check-storage-mountpoints, test/check-storage-mountpoints-btrfs, test/check-storage-mountpoints-lvm, test/check-storage-mountpoints-raid, test/check-storage-reclaim, test/vm.install
Fix tests on main Anaconda repository by unblocking Anaconda RPMs from PR testing. Also adapt for a new disk label of virtio block devices.
This reverts commit 9f59b69ea4a3d0aa10d89c9065c183ab73c5e118.
=> Revert "tests: do not update the anaconda packages till the wayland work reaches rawhide"

test/check-storage-cockpit
Cockpit renamed the btrfs "root subvolume" to "top-level" to avoid confusion with "/".
https://github.com/cockpit-project/cockpit/pull/21127
=> test: adjust for btrfs hidden subvolume rename to top-level

src/components/storage/ReclaimSpaceModal.jsx, src/components/storage/ReclaimSpaceModal.scss
=> Disable remove extended partition for EFI operation systems

src/components/storage/CockpitStorageIntegration.jsx, test/check-progress
Accessing the Cockpit storage editor outside the scenario selection step can cause unexpected issues during installation.  To prevent this, the dropdown item for the storage editor is now disabled when not on the storage entry page.
=> storage: restrict access to the storage editor to the scenario selection step

src/apis/storage_partitioning.js, src/components/storage/InstallationScenario.jsx, src/helpers/storage.js, test/check-storage-home-reuse, test/check-storage-home-reuse-e2e
=> home reuse: add check for unexpected existing mount points

src/components/localization/InstallationLanguage.jsx, src/components/localization/InstallationLanguage.scss, test/check-language, test/check-review, test/helpers/language.py
=> Improve the language screen from new design

scripts/makeupdates
It currently only works if you have run certain `make` targets - anaconda-webui.spec is not part of the version-controlled repo, it's generated. It seems safer to look for a file under version control.
I'm not sure the script is much use for anaconda-webui anyway - I don't think there's a mechanism to apply changes to the jsx files, for e.g. - but it doesn't hurt to improve this.
=> Fix scripts/makeupdates root detection

.github/workflows/nightly.yml, test/download-iso, test/run, test/vm.install
We want to test the compose untouched, that means anaconda-webui package that is inside the compose. That means we also need to checkout the anaconda-webui repository, before running the tests to the tag used in the compose.
This is problematic, because our support for testing composes did not yet land in rawhide, therefore no tag contains that currently.
Let's test against anaconda-webui from main branch, temporarily.
=> tests: fix nightly action for testing latest compose

.gitignore, test/anacondalib.py, test/prepare-report, test/run
This can be parsed from OpenQA tools, for writing our test results into Fedora Test Wiki.
=> tests: generate report.json for TEST_SCENARIO=compose-XYZ

src/components/review/ReviewConfiguration.jsx, src/components/steps.js, test/helpers/utils.py
There was mismatch in the option name between front-end and back-end.
=> Parse hidden_webui_pages option from anaconda.conf

.github/workflows/nightly.yml, test/run, test/vm.install
So that we are using for testing the same version of the Web UI source code (tests etc) that the anaconda-webui RPM has in the compose.
=> tests: when testing against a compose checkout the TAG used in the compose

test/helpers/installer.py
Next button is disabled when no disks are selected, we don't need the explicit sleep in the tests.
=> tests: remove sleep before clicking 'next'

test/check-storage-cockpit
Tests are now failing because pixel tests do not contain images with the Welcome screen.
=> Fix tests after adding Welcome screen

test/helpers/installer.py
Especially on the initial load, and especially when the task container is on heavy load, loading the page takes more than the default 15 seconds, resulting in test flakiness. Be more generous with the time there.
=> tests: double the time of the timeout when waiting for the initial page load

.cockpit-ci/container, test/run
When testing composes we checkout the git repository to the tag that anaconda-webui has in that compose. We do that so that the tests match the code tested.
However, there is some infra logic, that got more recently added, and is there for reporting to fedora wiki.
Let's copy the relevant files from master till these changes are part of the composes we are interested to test.
=> tests: fix old compose wiki reporting

src/actions/localization-actions.js, src/apis/localization.js, src/components/localization/InstallationLanguage.jsx, src/components/localization/InstallationLanguage.scss, src/components/localization/Keyboard.jsx, src/reducer.js, test/anacondalib.py, test/check-language, test/helpers/language.py, test/helpers/storage.py
=> Adding keyboard settings with localectl

test/check-storage-cockpit, test/helpers/installer.py, test/helpers/storage.py
Exiting the cockpit-storage page, does heavy operations, like creating partitioning, re-scanning disks etc.
Give it a bit more time as on heavy CI load this sometimes fails to load in time.
=> tests: increase timeout for dialog to load when exiting cockpit-storage

test/check-language, test/helpers/language.py
This fixes the following error that appears often in CI: testlib.Error: move target out of bounds: Cannot move beyond viewport (x: 1306, y: -2028)
=> tests: fix language switching case by bringing desired locale is in viewport

test/check-storage-cockpit, test/helpers/review.py, test/helpers/storage.py
This is needed because of an LVM2 bug which causes re-scanning to take forever.
The anaconda fix for rawhide is merged and released: https://github.com/rhinstaller/anaconda/pull/6140
For fedora-42 we need a workaround in the tests as PR is still not merged: https://github.com/rhinstaller/anaconda/pull/6234.
=> tests: increase timeout for when exiting cockpit-storage

.gitignore, test/machine_install.py, test/prepare-updates-img
So that we dont have to re-create it when running tests against other distro locally.
=> test: name updates.img according to the distro version

test/helpers/progress.py
This will make tests that failed exit earlier.
=> tests: e2e: when waiting for the reboot button to appear check for possible errors

test/wiki-report.py
By mistake the above commit removed the run method execution.
=> test: wiki-report: fix up for 8c64a6

src/apis/storage.js, src/components/storage/InstallationScenario.jsx, src/components/storage/scenarios/EraseAll.jsx, src/components/storage/scenarios/MountPointMapping.jsx, src/components/storage/scenarios/ReinstallFedora.jsx, src/components/storage/scenarios/UseConfiguredStorage.jsx, src/components/storage/scenarios/UseFreeSpace.jsx, src/components/storage/scenarios/index.js, test/anacondalib.py, test/check-storage-basic, test/check-storage-cockpit, test/check-storage-encryption, test/check-storage-erase-all, test/check-storage-erase-all-e2e, test/check-storage-home-reuse, test/check-storage-home-reuse-e2e, test/check-storage-reclaim, test/check-storage-reclaim-e2e, test/check-storage-use-free-space-e2e, test/helpers/storage.py
Scenarios are now presented with the following order:
* Re-install Fedora
* Use Free Space
* Mount Point Mapping
* Erase All
* Use Configured storage
Resolves: rhbz#2347151
=> storage: adjust scenario display order and default scenario selection

test/wiki-testmap.json
Non-E2E tests validate all expected checks without rebooting into the installed system, avoiding resource overhead. Instead, they verify the `fstab` file and the UI indicating partition changes (removal/resizing), providing assurance that the created storage layout aligns with expectations.
=> tests: Map some non-E2E test cases to the wiki test map

test/helpers/operating_systems.py
So that it is sufficient for the "Use free space" scenario.  If the test TestStorageReclaimExistingSystemWindows.testBasic
followed TestStorageReclaimExistingSystemFedora.testDeletePartition the space was not sufficient by a fraction of GB.
=> test: make the win "Basic data partition" leave a bit more space

pyproject.toml, test/check-storage-cockpit, test/check-storage-mountpoints
Resolves: rhbz#2353002
The tests and tests updates related to https://github.com/rhinstaller/anaconda/pull/6306
=> Add a basic test for MBR partition table created in Cockpit Storage

src/components/storage/CockpitStorageIntegration.jsx, test/check-storage-cockpit
Adjust existing test to cover for both biosboot end uefi boot modes.
Resolves: rhbz#2352953
=> storage: cockpit-storage: prevent bootloader partitions on MDRAID devices

test/machine_install.py
`setup` package introduce a change in rawhide, making the root account locked for security purposes by default in installation images.
For enabling our test suite to connect to the booted image this commit:
- Added a %pre section to unlock the root account
- Ensured sshd service starts
Reference: https://src.fedoraproject.org/rpms/setup/c/7ced36d60b67c9e74f7951123225200597e3d2fa
=> tests: unlock root account and start sshd in interactive defaults

src/components/storage/MountPointMapping.jsx
=> storage: mount point mapping: fix wrapping of the custom mount points rows

test/check-storage-home-reuse, test/check-storage-mountpoints
This was keeping devices busy after test teardown generating a series of test failures.
=> tests: kill rsync process in case it's keeping a mount busy

src/components/storage/CockpitStorageIntegration.jsx, test/check-storage-cockpit, test/helpers/storage.py
When an MD RAID device is deleted and a new one is immediately created using the same disks, the selected disks list will temporarily not include the parent disks. To handle this correctly, we first re-add the parent disks to the selection, then determine whether the new MD RAID device should replace them in the selected set.
Resolves: rhbz#2354798
=> storage: fix selected disk handling when replacing an MD RAID device

src/components/app.scss
=> Override globally modals min-width to stretch according to the contents

packaging/anaconda-webui.spec.in
Unpin when we are also ready with Patternfly 6 migration.
=> build: pin down cockpit-storaged version because of Patternfly 6 changes

test/vm.install
=> Anaconda needs latest pykickstart but image refresh is currently blocked on kernel regression

test/check-storage-reclaim
That prevents pulling cockpit storage from updates. That already contains PF6 and we are not ready for testing that.
=> tests: ensure that reclaim checkbox is selected before going to reclaim dialog

src/components/HeaderKebab.jsx
Just reinstalled fedora 41 and found a minor bug with the installer: you can't click outside the of the kebab dropdown menu to close it. 
This PR fixes that issue
=> fix: can't click outside of header dropdown to close it

packaging/anaconda-webui.spec.in
This reverts commit 5dd43fe92509004b4e5fcfcaa6b7361eb4c9314d.
We need cockpit-storaged, we should just not pin down the version.
=> Revert "build: stop requiring cockpit-storaged with Patternfly 5"

src/components/storage/InstallationScenario.jsx
Patternfly 6 does not expose isAriaDisabled property on radio buttons. https://www.patternfly.org/components/forms/radio/
=> components: storage: fix disabled radio buttons

src/components/AnacondaPage.jsx, src/components/AnacondaWizard.jsx, src/components/storage/InstallationMethod.jsx, src/components/storage/InstallationScenario.jsx
Rendering wizard pages in the background can trigger API calls to devices that may no longer exist, leading to errors.
We currently work around this by handling and silencing these errors [1] as a hotfix for Fedora 42, due to limited time to implement a proper fix.
This change takes first steps to a more robust approach by preventing the rendering of wizard pages entirely while cockpit-storage mode is active, avoiding invalid device accesses altogether.
[1] https://github.com/rhinstaller/anaconda-webui/commit/53f2ff
=> storage: avoid rendering wizard pages while Cockpit Storage is active

test/vm.install
This reverts commit b6702ead655b8290ff766d8949c148b6c1bc0bc1.
=> Revert "Anaconda needs latest pykickstart but image refresh is currently blocked on kernel regression"

.github/dependabot.yml, .github/workflows/dependabot.yml
The node cache must be handled when updating package.json, which is managed by our custom Dependabot GitHub workflow.
Previously, we weren't setting the [node-modules] label, so the workflow wasn't triggered. This change ensures that the workflow runs as intended.
=> infra: trigger dependabot workflow for updating node_modules

src/contexts/Common.jsx
Cockpit's spawn environment does not expose XDG_CURRENT_DESKTOP, so desktop detection via that variable was unreliable. This change uses `ps` to check for the presence of `gnome-shell` to infer if GNOME is running. Falls back to "UNKNOWN" otherwise.
=> Use process inspection to detect GNOME instead of XDG_CURRENT_DESKTOP

pyproject.toml, test/check-storage-basic, test/check-storage-erase-all, test/check-storage-home-reuse, test/check-storage-reclaim, test/check-users, test/wiki-testmap.json
Since bd2b83a730c97e4a72ed62475b0b49e7dd955301, that we introduced the disk_images test method decorator instead of the class attribute for specifing disks we can just have one wrapper class per file, making the test files slightly cleaner.
Pixel test references had to be updated with the new names.
=> tests: remove unnecessary class wrappers

test/machine_install.py
This reverts commit f51078b012384e75ae331f45001565530c573216.
This was fixed in lorax by: https://bodhi.fedoraproject.org/updates/FEDORA-2025-2d0f741832
See: https://bugzilla.redhat.com/show_bug.cgi?id=2364082
=> Revert "tests: unlock root account and start sshd in interactive defaults"

src/components/storage/InstallationScenario.jsx, src/components/storage/scenarios/index.js
Extracted hook calls into useScenariosAvailability to ensure React Hooks are invoked at the top level and in a consistent order. This prevents extra renders and avoids breaking the Rules of Hooks.
Resolves: INSTALLER-4202
=> fix: resolve unnecessary re-renders and hook rule violations in scenario availability

test/run
Avoid errors with the following pattern:
ERROR    Error: --disk /var/tmp/*.qcow2,format=qcow2,target=vda: Could
not define storage pool: operation failed: pool 'tmp' already exists
with uuid *
subprocess.CalledProcessError: Command '['virt-xml', '-c', 'qemu:///session', 'fedora-rawhide-boot-127.0.0.2-2201', '--update', '--add-device', '--disk', '/var/tmp/*.qcow2,format=qcow2,target=vda']' returned non-zero exit status 1.
=> test: avoid test failures because pool has been defined

org.cockpit-project.anaconda-webui.metainfo.xml
This ensures software centers and Cockpit do not get confused by the template ID named "Anaconda".
=> metainfo: Use the correct AppStream ID

test/check-storage-cockpit-e2e, test/fedora-wiki/wiki-testmap.json
https://fedoraproject.org/wiki/QA:Testcase_partitioning_webui_custom_with_swap
It's the last one that is not reported for Web UI in Wiki test results [1].
[1] https://fedoraproject.org/wiki/Test_Results:Current_Installation_Test
Resolves: INSTALLER-4146
=> tests: implement test scenario for E2E installation with SWAP

packaging/anaconda-webui.spec.in
This ensures Firefox is only required when installing on Fedora Workstation, while still avoiding the dependency on RHEL and other Fedora variants.
Fixes: INSTALLER-4189
=> Only require Firefox on Fedora Workstation

test/helpers/password.py, test/helpers/users.py
This commit c66f51f2cf38380a1008a644b3ea7313e6247abd introduces a autofocus logic in the code for the Root Password field, after the user enables root account creation. This was causing some flakiness in the tests which type super fact, as it would regain focus on the first password field, when the test would be already filling the second password field.
Fix this by waiting for the focus before starting typing.
=> tests: users: wait for password to be focused before starting typing

test/helpers/progress.py, test/helpers/storage.py
This triggers the mdadm --assemble failure early in the test when running with recent rawhide kernels where the operation is currently broken.
Doing so ensures that the RAID-related tests fail consistently and can be reliably matched through a naughty in bots, since there is no other stable pattern of failure detection at this point.
=> tests: explicitly invoke mdadm --assemble to trigger known failure on rawhide

test/anacondalib.py
And test runners do not always exist in the same data center.
Example failure: https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-6549-a888a48b-20250812-071735-fedora-rawhide-boot-anaconda-pr-6549-rhinstaller-anaconda-webui/TestStorageMountPoints-testMultipleDisks-review-multiple-disks-delta.png
=> tests: ignore timezone in review screen as this is autodetected

test/check-storage-use-free-space
Rolling releases like debian testing don't have VERSION.
=> tests: do not check exact version for debian testing

.github/workflows/test-compose.yml, test/download-iso, test/helpers/compose_path.py, test/run, test/vm.install
- Add matrix to test against both rawhide and Fedora 43 when no specific compose_id is provided
- Maintain manual runs with specific compose_id
=> infra: add matrix strategy to test-compose workflow

.gitignore, Makefile, build.js, packaging/anaconda-webui.spec.in, src/components/Error.jsx, src/components/HeaderKebab.jsx, src/components/app.jsx, src/contexts/Common.jsx, src/helpers/product.js
Adds os-release PRETTY_NAME, Anaconda version and Anaconda UI version to Bugzilla template. This enhancement improves the context provided in error reports, making it easier to identify the environment in which issues occur.
Also, now that version information is being used in more than one place, the way it is collected/used was refactored to have that cached on a proper Context. This had a side effect on the "about" modal which now loads the version information instantly.
[before-context.webm](https://github.com/user-attachments/assets/6890a1d0-485e-4096-8a87-05370cd19b97)
[after-context.webm](https://github.com/user-attachments/assets/c3b11596-f87d-4daa-b941-290b8ae7a0a4)
=> Add debugging info to BZ template

test/check-storage-reclaim-e2e
Tests started failing like this: https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-6600-a0b25edd-20250901-121612-fedora-43-boot-anaconda-pr-6600-rhinstaller-anaconda-webui/TestStorageReclaim_E2E-testReclaimShrink-fedora-43-boot-127.0.0.2-2301-FAIL.png 
Remove 1GB less from the debian root partition on the reclaim test.
=> tests: debian reclaim space: fix new size it too small error

test/fedora-wiki/wiki-report.py
ResTuple can obtain release information from the compose ID.
Tested with manual report:  `test/fedora-wiki/wiki-report.py ./test/report.json`
```
kkoukiou@easy:~/repos/anaconda-webui$ cat ./test/report.json 
{
"metadata": {
"compose": "Fedora-43-20250821.n.0",
"test_env": "qemu-x86_64"
},
"tests": [
{
"arch": "x86_64",
"test_name": "TestStorageCockpitIntegration.testBtrfsSubvolumes",
"firmware": "BIOS",
"status": "pass",
"error": null
}
]
}
```
which was indeed reported here: 
https://fedoraproject.org/wiki/Test_Results:Fedora_43_Branched_20250821.n.0_Installation
=> test: fedora-wiki: remove hardcoded release when reporting to Fedora Wiki

src/components/datetime/Timezone.jsx, test/check-timezone, test/helpers/timezone.py
This should resolve the `RangeError` that is thrown during the installation of Fedora 43 when the time zone contains multiple slashes.
For example, a `RangeError` is thrown when the timezone is: `America/Argentina/Buenos_Aires`.
Example:
```ts
const timezone = 'America/Argentina/Buenos_Aires';
const [reg, cty] = timezone.split('/');
console.log(reg, cty); // output: America Argentina
const [reg, ...cty] = timezone.split('/');
console.log(reg, cty.join('/')); // output: America Argentina/Buenos_Aires
```
=> fix(timezone): correctly parse timezones with multiple slashes

test/fedora-wiki/wiki-report.py
Setting `compose='20250910.n.0'` is wrong. It's not breaking anything because wikitcms [1] uses cid if present and ignores any release/milestone/compose values. However, release/milestone/compose and cid are alternative ways to try and identify the thing we're reporting for.
[1] https://pagure.io/fedora-qa/python-wikitcms/blob/main/f/src/wikitcms/wiki.py
=> tests: remove compose from the ResTuple

Makefile, packaging/anaconda-webui.spec.in, src/branding/fedora.scss, src/components/AnacondaHeader.jsx, src/index.html
Consume branding for Fedora from cockpit/static/branding.css
=> Consume branding for Fedora from cockpit/static/branding.css

pyproject.toml, src/helpers/storage.js, test/check-storage-mountpoints, test/helpers/storage.py
The disks were not detected as LUKS encrypted because getLockedLUKSDevices was checking only child devices, not disks.
Also add test scenario for mount-point-mapping unlock flow for /home on encrypted second disk (whole disk).
Finally fix the comments on the getDeviceAncestors & getDeviceChildren to reflect that they are not returning the device itself in the returned list. This was probably an older behavior.
Resolves: rhbz#2396646
=> storage: detect locked LUKS on selected disks including whole-disk LUKS

test/anacondalib.py, test/check-progress
Since 5ab1a92cd0b328d0376875fef58698c4cbab8e76 icons are now rendered stable for pixel testing.
=> tests: there is not need to ignore icons any more

Makefile, test/machine_install.py
Unpack the combined payload artifact from bots into tmp/<payload> during ‘make payload’.
Serve that directory locally in tests and point Anaconda to it:
- liveimg: use http://10.0.2.2:<port>/liveimg.tar.gz
For future we can now also consume dnf paylaod as follows:
- dnf: use repo baseurl http://10.0.2.2:<port>/repo/
Note: This is part of: https://github.com/rhinstaller/anaconda-webui/pull/1023
=> tests: support new payload consumed from bots repository

src/components/storage/storage-configuration/DiskEncryption.jsx
The previous selector that was displayed in the disk enctryption screen is using APIs [1] which is not supported by Gnome [2].
[1] SetCompositorLayouts, XLayouts are based on localed
[2] https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7761
=> keyboard: in Gnome spawn Gnome keyboard settings in storage configuration screen

src/components/storage/installation-method/InstallationMethod.jsx
The mis-spelled page ID was causing the page notifications from the installation method page to not be shown in the UI, as the step id for the notification was incorrectly set.
=> storage: installation-method: the screen id is 'anaconda-screen-method'
